### ISSUE TITLE
[CoL] Crash on load after updating from 3.0.9 to 3.1.1

### ISSUE THREAD

**Issue by drakray** [wildcardgamez/Buddycards-Core#6]
https://pastebin.com/HfXB3aRb
<details>
<summary>snipet</summary>

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.elrol.data.CardSetData.lambda$registerSet$3(CardSetData.java:80) ~[buddycustomcards-1.0.10.jar%23135!/:1.0.10] {re:classloading}
-- MOD buddycards --
Details:
	Mod File: 1-buddycards-1.18.2-3.1.1.jar
	Failure message: Buddycards Core (buddycards) encountered an error during the common_setup event phase
		java.lang.NoSuchFieldError: DEFAULT_MEDAL_PROPERTIES
	Mod Version: 1.18.2-3.1.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: DEFAULT_MEDAL_PROPERTIES
Stacktrace:
	at dev.elrol.data.CardSetData.lambda$registerSet$3(CardSetData.java:80) ~[buddycustomcards-1.0.10.jar%23135!/:1.0.10] {re:classloading}
	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:214) ~[forge-1.18.2-40.1.54-universal.jar%23294!/:?] {re:classloading}
	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:446) ~[forge-1.18.2-40.1.54-universal.jar%23294!/:?] {re:classloading}
	at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:376) ~[forge-1.18.2-40.1.54-universal.jar%23294!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.54.jar%23291!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.54.jar%23290!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
```
</details>

**Comment by wildcardgamez** [comment]
Ah that makes sense. I generified the name of a default property without thinking about proper expansion mods making use of it. Ill let the dev for the mod know, it isnt a bug with this mod though so Ill close this issue
